version: '2'

services:
  wpe:
    restart: always
    build: ./
    privileged: true
    environment:
      - WPE_URL=http://pyflask:5000/
    ports:
      - 8080:8080
    links:
      - ui_server
    depends_on:
      - ui_server

  ui_server:
    restart: always
    image: johnjansen/pyflask_arm
    expose:
      - "5000"

  hal:
    # hardware abstraction layer
    image: alpine
    tty: true

  pal:
    # payment abstraction layer
    image: alpine
    tty: true

  ral:
     # RFID abstraction layer
    image: alpine
    tty: true
  
  debug:
    image: alpine
    tty: true
