version: '2'

services:
  wpe:
    restart: always
    build: ./wpe
    privileged: true
    environment:
      - WPE_URL=http://uix:5000/
    ports:
      - 8080:8080
    links:
      - uix
    depends_on:
      - uix

  uix:
    restart: always
    image: johnjansen/pyflask_arm
    expose:
      - "5000"
    links:
      - hal
      - pal
      - ral
    depends_on:
      - hal
      - pal
      - ral

  hal:
    # hardware abstraction layer
    build: ./hal

  pal:
    # payment abstraction layer
    build: ./pal

  ral:
     # RFID abstraction layer
    build: ./ral
