version: '2'

services:
  wpe:
    restart: always
    build: ./
    privileged: true
    ports:
      - 8080:8080
  cronlog:
    restart: always
    image: alpine
    command: while sleep 1; do date; done
