version: '2'
volumes:
    logstash_pipeline:
# services:
#   logstash:
#     image: blacktop/logstash
#     volumes:
#       - 'logstash_pipeline:/usr/share/logstash/pipeline/'
  wpe:
    restart: always
    build: ./wpe
    privileged: true
    environment:
      - WPE_URL=http://uix:5000/
    ports:
      - 8080:8080
    links:
      - uix
    depends_on:
      - uix

  uix:
    restart: always
    build: ./uix
    privileged: true
    expose:
      - "5000"
    links:
      - hal
      - pal
      - ral
    depends_on:
      - hal
      - pal
      - ral

  hal:
    # hardware abstraction layer
    build: ./hal
    privileged: true

  pal:
    # payment abstraction layer
    build: ./pal
    privileged: true

  ral:
     # RFID abstraction layer
    build: ./ral
    privileged: true
